-- MLP Member

DROP TABLE MLPMEMBER;
DROP SEQUENCE SEQ_MM;

CREATE SEQUENCE SEQ_MM;

CREATE TABLE MLPMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL UNIQUE,
	PW VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(500) NOT NULL,
	PHONE VARCHAR2(2000) NOT NULL,
	EMAIL VARCHAR2(2000) NOT NULL
);

INSERT INTO MLPMEMBER 
VALUES(SEQ_MM.NEXTVAL, 'dkwjd', '1129', '송아정', '010-9861-3334', 'dkwjd@gmail.com');

INSERT INTO MLPMEMBER 
VALUES(0, 'ADMIN', 'ADMIN', '관리자', '010-0000-0000', 'ADMIN@admin.com');


SELECT * FROM MLPMEMBER 
ORDER BY NO;

COMMIT;