
-- 5_WEB. JSP10_ASYNC
DROP TABLE BIKE_TB;

CREATE TABLE BIKE_TB(
	ADDR_GU VARCHAR2(4000),
	CONTENT_IT NUMBER PRIMARY KEY,
	CONTENT_NM VARCHAR2(4000),
	NEW_ADDR VARCHAR2(4000),
	CRADLE_COUNT NUMBER,
	LONGITUDE NUMBER,
	LATITUDE NUMBER
);

SELECT * FROM BIKE_TB;

COMMIT;

DELETE  BIKE_TB;

-- 5_WEB. JSP11_MyBoard_Mybatis

SELECT * FROM MYBOARD;

------------------------------------------------------------------

-- MLP Member

DROP TABLE MLPMEMBER;
DROP SEQUENCE SEQ_MM;

CREATE SEQUENCE SEQ_MM;

CREATE TABLE MLPMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL UNIQUE,
	PW VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(500) NOT NULL,
	PHONE VARCHAR2(2000) NOT NULL,
	EMAIL VARCHAR2(2000) NOT NULL
);

INSERT INTO MLPMEMBER 
VALUES(SEQ_MM.NEXTVAL, 'dkwjd', '1129', '송아정', '010-9861-3334', 'dkwjd@gmail.com');

INSERT INTO MLPMEMBER 
VALUES(0, 'ADMIN', 'ADMIN', '관리자', '010-0000-0000', 'ADMIN@admin.com');


SELECT * FROM MLPMEMBER 
ORDER BY NO;

COMMIT;