
-- 5_WEB. JSP10_ASYNC
DROP TABLE BIKE_TB;

CREATE TABLE BIKE_TB(
	ADDR_GU VARCHAR2(4000),
	CONTENT_IT NUMBER PRIMARY KEY,
	CONTENT_NM VARCHAR2(4000),
	NEW_ADDR VARCHAR2(4000),
	CRADLE_COUNT NUMBER,
	LONGITUDE NUMBER,
	LATITUDE NUMBER
);

SELECT * FROM BIKE_TB;

COMMIT;

DELETE  BIKE_TB;

-- 5_WEB. JSP11_MyBoard_Mybatis

SELECT * FROM MYBOARD;