-- MEMBER (회원)
DROP TABLE COMMUNITYMEMBER;
DROP SEQUENCE SEQ_CM;

CREATE SEQUENCE SEQ_CM NOCACHE;

CREATE TABLE COMMUNITYMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL UNIQUE,
	PW VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(500) NOT NULL,
	PHONE VARCHAR2(1000) NOT NULL, 
	ENABLED VARCHAR(10) CHECK(ENABLED IN ('Y', 'N'))
);

INSERT INTO COMMUNITYMEMBER
VALUES(SEQ_CM.NEXTVAL, 'ADMIN', 'ADMIN', '관리자', '010-1111-1111', 'Y')

SELECT * FROM COMMUNITYMEMBER;