-- BOARD (게시판)
DROP TABLE COMMUNITYBOARD;
DROP SEQUENCE SEQ_CB;

CREATE SEQUENCE SEQ_CB NOCACHE;
CREATE TABLE COMMUNITYBOARD(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO COMMUNITYBOARD
VALUES(SEQ_CB.NEXTVAL, '관리자', '테스트 제목', '테스트 글입니다.', SYSDATE);

SELECT * FROM COMMUNITYBOARD;

