DROP TABLE ANSWERBOARD;
DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;

-- 글 번호 시퀀스
CREATE SEQUENCE BOARDNOSQ NOCACHE;

-- 그룹 번호 시퀀스
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL, 
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

-- 첫번째 글 작성 
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '첫번째 글', '1번 글입니다!!', '유저1', SYSDATE);

-- 두번째 글 작성 
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '두번째 글', '2번 글입니다!!', '유저2', SYSDATE);

-- 1번 글의 답변글 작성
-- 부모(=1번 글)와 같은 GROUPNO
-- 부모의 GROUPSEQ+1, 부모의 TITLETAB+2 
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, 
	   (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1), 
	   (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	   (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+2, 
       'RE:첫번째 글', '1번글에 답변 글입니다.', '유저2', SYSDATE);

-- 세번째 글 작성 
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '세번째 글', '3번 글입니다!!', '유저3', SYSDATE);


-- 답글 작성 (두번째 글)
-- 부모(=2번 글)와 같은 GROUPNO
-- 부모의 GROUPSEQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, 
	   (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2), 
	   (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	   (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+2, 
       'RE:RE:두번째 글', '2번글에 답변 글에 답변글입니다.', '유저1', SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

-- 답글 작성 (두번째 글 : NO가 2개 )
-- 부무ㅗ와 같은 GROUPNO에서 부 모 보다 큰 GROUNSQ 글을 한다.

-- 답변글 작성 (두번째글 : NO가 2)
-- 부모와 같은 GROUPPNO 에서
-- 부모보 다 큰 GROUPSQ 글들을 GROUPSEQ+1
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
	AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+2,
		'RE:RE:두 번째 글', '2반 글 답변 글에 두번째임', '유저3', SYSDATE);
	

-- 답변 작성 (NO-7)
-- 1. UPDATE 
--		부모와 같은 GROUPNO이고 부모의 GROUPSQ보다 큰 글들의 
-- 		GROUPSQ+1 

-- 2. INSERT 
-- 		부모와 같은 GROUPNO, 부모의 GROUPSQ+1, 부모의 TITLETAB+2

UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
	AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+2,
		'R:RE:두 번째 글!!!', '2번 글 답변 글에 세번째임', '유저4', SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;